# Generated by Django 2.2.16 on 2020-09-29 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='наименование')),
                ('article', models.CharField(max_length=20, null=True, unique=True, verbose_name='артикул')),
                ('description', models.TextField(null=True, verbose_name='описание')),
                ('price', models.FloatField(verbose_name='цена')),
                ('img', models.ImageField(default='default.jpg', upload_to='media', verbose_name='фото')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='количество')),
                ('price_summ', models.FloatField(verbose_name='сумма заказа')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Product', verbose_name='товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.CustomUser', verbose_name='пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_summ', models.FloatField(verbose_name='сумма заказа')),
                ('products', models.ManyToManyField(blank=True, to='home.ProductAdd')),
                ('user_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.CustomUser', verbose_name='владелец')),
            ],
        ),
    ]
